version: 0.4.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet build src /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION% /verbosity:minimal

    dotnet pack src/FsNetMQ -c Release --no-build /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet test src/FsNetMQ.Tests/ -- --fail-on-focused-tests --summary
artifacts:
- path: '**/*.nupkg'
